apiVersion: v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  templates:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: kalyandockernew/vprofiledb:v1
          args:
            - "ignore-db-dir=lost+found"
          volumeMounts:
            - mounthPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-07d77ffac9a25401d
            fsType: ext4
